export default {
    myPages: {},
    cart: {
        items: [],
        address: {},
        selectedPayment: {},
        loaded: false
    },
    globalPopup: {},
    onboardingPopup: {},
    isProUser: false,
    myProductsList: false,
    digitalOrderPopup: null,
    displayData: {},
    orderComplete: null,
    email: null,
    myInfo: null,
    myPrivateInfo: null,
    notifyFulfillments: 0,
    myConnectId: '',
    inventory: {},
    plan: {
        loaded: false,
        pro: false
    },
    showHeaderShop: false,
    loaded: false,
    uid: false,
    profilePic: false,
    username: false,
    accountCreated: false,
    test: 'success!',
    friendsData: {},
    friendsDataArray: [],
    authError: false,
    myWork: {},
    defaultState: {
            cart: {
            items: [],
            address: {},
            selectedPayment: {},
            loaded: false
        },
        globalPopup: {},
        onboardingPopup: {},
        isProUser: false,
        myProductsList: false,
        digitalOrderPopup: null,
        displayData: {},
        orderComplete: null,
        email: null,
        myInfo: null,
        myPrivateInfo: null,
        notifyFulfillments: 0,
        myConnectId: '',
        inventory: {},
        plan: {
            loaded: false,
            pro: false
        },
        showHeaderShop: false,
        loaded: false,
        uid: false,
        profilePic: false,
        username: false,
        accountCreated: false,
        test: 'success!',
        friendsData: {},
        friendsDataArray: [],
        authError: false,
        myWork: {},
    }
}